repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint core rest-api
        language: system
        types:
          - python
        args:
          - "--rcfile=.pylintrc"
          - "--load-plugins=pylint.extensions.docparams"
        #          - "-rn"
        #          - "-sn"
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt
        language: system
        pass_filenames: false
        stages:
          - commit