logging:
  level: INFO
  format: '%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] - %(message)s'

database:
  user: finance_adm
  password: finance_adm1234
  host: localhost
  port: 5432
  database: finance
  echo: False
  expire_on_commit: False
